In [1]:
!pip install openai

Requirement already satisfied: openai in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (2.8.1)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (4.3.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (0.27.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (2.7.1)
Requirement already satisfied: sniffio in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from openai) (4.11.0)
Requirement already satisfied: idna>=2.8 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: certifi in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->openai) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.2 in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.18.2)
Requirement already satisfied: colorama in c:\users\marvin scifo\appdata\local\programs\python\python312\lib\site-packages (from tqdm>4->openai) (0.4.6)

[notice] A new release of pip is available: 24.1.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
import os
from dotenv import load_dotenv
from openai import AsyncOpenAI
import pandas as pd
import re
import json
import asyncio

env_path = '.env'
load_dotenv(dotenv_path=env_path)

api_key = os.environ.get("OPENROUTER_API_KEY")

if not api_key:
    raise ValueError("OpenRouter API key not found. Please set OPENROUTER_API_KEY in your .env file.")

In [19]:
df = pd.read_csv("../scraper/investor_articles_full.csv")

df

,body_text,category,link,scraped_at,title
0,"JOHANNESBURG, investor.id —Para pemimpin dan d...",international,https://investor.id/international/418386/ktt-g...,2025-11-21T18:07:41.810501,KTT G20 Tetap Berjalan Tanpa AS dan Trump
1,"JAKARTA,investor.id-Kementerian Komunikasi dan...",business,https://investor.id/business/418353/cloudflare...,2025-11-21T18:07:42.880177,Cloudflare Dituding Lindungi Ribuan Situs Judo...
2,"JAKARTA, investor.id – Konglomerasi bisnis asa...",market,https://investor.id/market/418356/dana-jumbo-p...,2025-11-21T18:07:43.961976,Dana Jumbo Posco untukTender OfferSGRO
3,"JAKARTA, investor.id- Emiten komponen otomotif...",corporate-action,https://investor.id/corporate-action/418373/em...,2025-11-21T18:07:45.091613,Emiten TP Rachmat (DRMA) Mau Akuisisi 82% Saha...
4,"JAKARTA, investor.id- PT Teknologi Karya Digit...",corporate-action,https://investor.id/corporate-action/418360/tr...,2025-11-21T18:07:46.183802,"TRON - NBRI Jalin Kemitraan, Pacu Inovasi Kend..."
5,"JAKARTA, investor.id- Komisaris Independen PT ...",corporate-action,https://investor.id/corporate-action/418359/ko...,2025-11-21T18:07:47.300577,Komisaris Independen Telkom Indonesia (TLKM) M...
6,"JAKARTA, investor.id- Indeks harga saham gabun...",stock,https://investor.id/stock/418382/prediksi-ihsg...,2025-11-21T18:07:48.412238,"Prediksi IHSG dan Rekomendasi Saham Senin, 24 ..."
7,"JAKARTA, investor.id- Indeks harga saham gabun...",stock,https://investor.id/stock/418377/ihsg-turun-ti...,2025-11-21T18:07:49.527607,"IHSG Turun Tipis, 5 Saham Justru Kasih Cuan Be..."
8,"JAKARTA, investor.id- Wakil Menteri Keuangan (...",finance,https://investor.id/finance/418387/penyerapan-...,2025-11-21T18:07:50.607732,"Penyerapan Subsidi Bunga KUR Capai Rp 20,3 Tri..."
9,"JAKARTA, investor.id- Kredit bermasalah yang d...",finance,https://investor.id/finance/418383/npl-kur-228...,2025-11-21T18:07:51.686879,"NPL KUR 2,28% per Oktober 2025"
10,"JAKARTA, investor.id- Menteri Pertanian (Menta...",business,https://investor.id/business/418378/30-titik-p...,2025-11-21T18:07:52.837771,"30 Titik Pabrik Pakan akan Dibangun Awal 2026,..."
11,"TANGERANG, investor.id– PT Toyota Astra Motor ...",business,https://investor.id/business/418379/toyota-vel...,2025-11-21T18:07:53.972513,"Toyota Veloz Hybrid Meluncur di GJAW 2025, Buk..."
12,"JAKARTA, investor.id– Penempatan dana pemerint...",finance,https://investor.id/finance/418338/pertumbuhan...,2025-11-21T18:07:55.104431,Pertumbuhan Kredit Baru Terasa di Akhir Tahun
13,"JAKARTA, investor.id– Putusan Mahkamah Konstit...",business,https://investor.id/business/418311/hgu-dipang...,2025-11-21T18:07:56.205076,"HGU Dipangkas, Investor IKN Harus Diberi Kepas..."
14,"JAKARTA, investor.id- Komisi Pemberantasan Kor...",national,https://investor.id/national/418276/kpk-serahk...,2025-11-21T18:07:57.336359,KPK Serahkan Barang Rampasan Rp883 Miliar kepa...
15,"JAKARTA, investor.id- Minat investor ritel Ind...",market,https://investor.id/market/418384/aplikasi-bit...,2025-11-21T18:07:58.415512,"Aplikasi Bitcoin Makin Diminati Pemula, Pelaja..."
16,"JAKARTA, investor.id- Perbankan asal Swiss, UB...",market,https://investor.id/market/418362/harga-emas-d...,2025-11-21T18:07:59.560567,Harga Emas Diteropong Bakal Sentuh Titik Ini d...
17,"JAKARTA, investor.id– Ketua Dewan Ekonomi Nasi...",macroeconomy,https://investor.id/macroeconomy/415536/1-tahu...,2025-11-21T18:08:00.736892,1 Tahun Prabowo Versi Luhut
18,"JAKARTA, investor.id-Presiden Prabowo Subianto...",macroeconomy,https://investor.id/macroeconomy/414464/sekola...,2025-11-21T18:08:01.927441,Sekolah Garuda: Ikhtiar Mencetak SDM Berkualit...
19,"JAKARTA, investor.id- Saham PT Bank Rakyat Ind...",market,https://investor.id/market/418179/ramalan-soal...,2025-11-21T18:08:03.011471,Ramalan soal Saham BBRI Terbukti
20,"JAKARTA, investor.id- PT Adaro Andalan Indones...",market,https://investor.id/market/418138/muncul-pengu...,2025-11-21T18:08:04.177019,Muncul Pengumuman Resmi Dividen Interim Rp 538...
21,"JAKARTA, investor.id- Saham emiten Grup Sinar ...",market,https://investor.id/market/418161/laba-emiten-...,2025-11-21T18:08:05.281284,"Laba Emiten Naik 107%,BookValueRp 15.500, Saha..."
22,"JAKARTA, investor.id- Harga emas batangan mili...",market,https://investor.id/market/418165/prediksi-har...,2025-11-21T18:08:06.447608,Prediksi Harga Emas Antam (ANTM) Jumat 21 Nove...
23,"JAKARTA, investor.id– Emiten Grup Salim, PT In...",market,https://investor.id/market/418154/saham-murah-...,2025-11-21T18:08:07.590807,Saham Murah Emiten Grup Salim

In [20]:
df["body_text"] = df["body_text"].apply(
    lambda x: re.sub(r"^[^—–-]*[—–-]\s*", "", x)
)

# Jangan run code ini sebelum csv dibaca ulang

In [21]:
df

,body_text,category,link,scraped_at,title
0,Para pemimpin dan delegasi dari negara-negara ...,international,https://investor.id/international/418386/ktt-g...,2025-11-21T18:07:41.810501,KTT G20 Tetap Berjalan Tanpa AS dan Trump
1,Kementerian Komunikasi dan Digital (Kemkomdigi...,business,https://investor.id/business/418353/cloudflare...,2025-11-21T18:07:42.880177,Cloudflare Dituding Lindungi Ribuan Situs Judo...
2,"Konglomerasi bisnis asal Korea Selatan, Posco ...",market,https://investor.id/market/418356/dana-jumbo-p...,2025-11-21T18:07:43.961976,Dana Jumbo Posco untukTender OfferSGRO
3,Emiten komponen otomotif milik konglomerat TP ...,corporate-action,https://investor.id/corporate-action/418373/em...,2025-11-21T18:07:45.091613,Emiten TP Rachmat (DRMA) Mau Akuisisi 82% Saha...
4,PT Teknologi Karya Digital Nusa Tbk (TRON) ata...,corporate-action,https://investor.id/corporate-action/418360/tr...,2025-11-21T18:07:46.183802,"TRON - NBRI Jalin Kemitraan, Pacu Inovasi Kend..."
5,Komisaris Independen PT Telkom Indonesia (Pers...,corporate-action,https://investor.id/corporate-action/418359/ko...,2025-11-21T18:07:47.300577,Komisaris Independen Telkom Indonesia (TLKM) M...
6,Indeks harga saham gabungan (IHSG) diprediksi ...,stock,https://investor.id/stock/418382/prediksi-ihsg...,2025-11-21T18:07:48.412238,"Prediksi IHSG dan Rekomendasi Saham Senin, 24 ..."
7,"Indeks harga saham gabungan (IHSG) hari ini, J...",stock,https://investor.id/stock/418377/ihsg-turun-ti...,2025-11-21T18:07:49.527607,"IHSG Turun Tipis, 5 Saham Justru Kasih Cuan Be..."
8,Wakil Menteri Keuangan (Wamenkeu) Suahasil Naz...,finance,https://investor.id/finance/418387/penyerapan-...,2025-11-21T18:07:50.607732,"Penyerapan Subsidi Bunga KUR Capai Rp 20,3 Tri..."
9,Kredit bermasalah yang dipotret dari rasionon-...,finance,https://investor.id/finance/418383/npl-kur-228...,2025-11-21T18:07:51.686879,"NPL KUR 2,28% per Oktober 2025"
10,"Menteri Pertanian (Mentan), Andi Amran Sulaima...",business,https://investor.id/business/418378/30-titik-p...,2025-11-21T18:07:52.837771,"30 Titik Pabrik Pakan akan Dibangun Awal 2026,..."
11,PT Toyota Astra Motor (TAM) resmi meluncurkan ...,business,https://investor.id/business/418379/toyota-vel...,2025-11-21T18:07:53.972513,"Toyota Veloz Hybrid Meluncur di GJAW 2025, Buk..."
12,Penempatan dana pemerintah di Himpunan Bank Mi...,finance,https://investor.id/finance/418338/pertumbuhan...,2025-11-21T18:07:55.104431,Pertumbuhan Kredit Baru Terasa di Akhir Tahun
13,Putusan Mahkamah Konstitusi (MK) yang memangka...,business,https://investor.id/business/418311/hgu-dipang...,2025-11-21T18:07:56.205076,"HGU Dipangkas, Investor IKN Harus Diberi Kepas..."
14,Komisi Pemberantasan Korupsi (KPK) menyerahkan...,national,https://investor.id/national/418276/kpk-serahk...,2025-11-21T18:07:57.336359,KPK Serahkan Barang Rampasan Rp883 Miliar kepa...
15,Minat investor ritel Indonesia terhadap aset c...,market,https://investor.id/market/418384/aplikasi-bit...,2025-11-21T18:07:58.415512,"Aplikasi Bitcoin Makin Diminati Pemula, Pelaja..."
16,"Perbankan asal Swiss, UBS menaikkan prediksi h...",market,https://investor.id/market/418362/harga-emas-d...,2025-11-21T18:07:59.560567,Harga Emas Diteropong Bakal Sentuh Titik Ini d...
17,"Ketua Dewan Ekonomi Nasional (DEN), Luhut Bins...",macroeconomy,https://investor.id/macroeconomy/415536/1-tahu...,2025-11-21T18:08:00.736892,1 Tahun Prabowo Versi Luhut
18,Presiden Prabowo Subiantomenginisiasi pembangu...,macroeconomy,https://investor.id/macroeconomy/414464/sekola...,2025-11-21T18:08:01.927441,Sekolah Garuda: Ikhtiar Mencetak SDM Berkualit...
19,Saham PT Bank Rakyat Indonesia Tbk (BBRI) atau...,market,https://investor.id/market/418179/ramalan-soal...,2025-11-21T18:08:03.011471,Ramalan soal Saham BBRI Terbukti
20,PT Adaro Andalan Indonesia Tbk (AADI) mengumum...,market,https://investor.id/market/418138/muncul-pengu...,2025-11-21T18:08:04.177019,Muncul Pengumuman Resmi Dividen Interim Rp 538...
21,"Saham emiten Grup Sinar Mas, PT Pabrik Kertas ...",market,https://investor.id/market/418161/laba-emiten-...,2025-11-21T18:08:05.281284,"Laba Emiten Naik 107%,BookValueRp 15.500, Saha..."
22,Harga emas batangan milik PT Aneka Tambang ata...,market,https://investor.id/market/418165/prediksi-har...,2025-11-21T18:08:06.447608,Prediksi Harga Emas Antam (ANTM) Jumat 21 Nove...
23,"Emiten Grup Salim, PT Indofood CBP Sukses Makm...",market,https://investor.id/market/418154/saham-murah-...,2025-11-21T18:08:07.590807,Saham Murah Emiten Grup Salim

In [38]:
client = AsyncOpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,
    default_headers={"HTTP-Referer": "http://localhost:5000"}
)

In [28]:
ner_prompts = 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{{"entity": Entity Name 1, "type": Entity Type 1}}, {{"entity": Entity Name 2, "type": Entity Type 2}}, {{"entity": Entity Name 3, "type": Entity Type 3}}, ....]. \n\nParagraph: {para}\n\n Key Words: '
summary_prompts = "Here is a paragraph. Please give a summary of the paragraph. \n\nParagraph: {para}\n\n Summary: "

In [29]:
user_prompts = df['body_text']
system_prompt = "You are the smartest AI assistant"

In [30]:
processed_ner_prompts = []
processed_summary_prompts = []

for i in user_prompts:
    processed_ner_prompts.append(ner_prompts.format(para=i))
    processed_summary_prompts.append(summary_prompts.format(para=i))

print(processed_ner_prompts)
print(processed_summary_prompts)

['Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Para pemimpin dan delegasi dari negara-negara makmur serta negara berkembang dijadwalkan berkumpul pada akhir pekan ini untuk menghadiri penyelenggaraan konferensi tingkat tinggi (KTT) G20 di Johannesburg, Afrika Selatan (Afsel). Namun, pertemuan tahun ini diwarnai aksi boikot dari Presiden Amerika Serikat (AS) Donald Trump dan pemerintahannya, dengan tidak mengirimkan perwakilan sama sekali.\n\nKTT G20 pertama yang digelar di benua Afrika itu akan dihadiri oleh perwakilan dari 42 negara. Absennya AS, salah satu anggota pendiri sekaligus pihak yang seharusnya mengambil alih presidensi bergilir G20 di Johannesburg, menjadi sorotan utama dan mendominasi percakapan menjelang pertemuan.\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Kementerian Komunikasi dan Digital (Kemkomdigi) membeberkan fakta penting terkait layanan Cloudflare di Indonesia, pasca gangguan layanan yang mengakibatkan lumpuhnya beberapa layanan aplikasi dan internet global.\n\nBerdasarkan temuan Kemkomdigi, Cloudflare ternyata melindungi ribuan situs judi online (judol) melalui penyamaran alamatInternet Protokol(IP), dan mempercepat perpindahan domain untuk menghindari pemblokiran konten. Berdasarkan 10.000 datasamplingsitus judi online yang ditangani pada periode 1-2 November 2025, Kemkomdigi menyebut, lebih dari 76% diantaranya menggunakan layanan Cloudflare.\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Konglomerasi bisnis asal Korea Selatan, Posco International mengatakan telah menyiapkan dana jumbo untuk melakukan penawaran tender wajib (mandatory tender offer) sebanyak 34,28% saham PT Sampoerna Agro Tbk (SGRO) setelah menjadi pengendali baru emiten sawit tersebut. Pada 19 November 2025, Posco melalui anak usahanya, Agpa Pte Ltd telah membeli sebanyak 1,19 miliar saham atau 65,72% saham SGRO dari Twinwood Family Holdings Limited (Grup Sampoerna) senilai US$ 566,49 juta atau setara Rp 9,44 triliun.\n\n“Tujuan akuisisi adalah untuk perluasan sinergi bisnis sawit di Indonesia,” kata Manajemen Posco International dalam keterangan resmi kepada Bursa Korea (Korea Exchange), Kamis (20/11/2025).\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Emiten komponen otomotif milik konglomerat TP Rachmat, PT Dharma Polimetal Tbk (DRMA) berencana mengakuisisi saham perusahaan asal Malaysia, PT Mah Sing Indonesia (MSI).\n\nPresident Direktur Dharma Polimetal (DRMA) Irianto Santoso mengungkap rencana perseroan untuk mengakuisisi 82% saham PT Mah Sing Indonesia (MSI) dengan nilai transaksi sekitar Rp 41 miliar.\n\n“Saat ini kami berada pada tahap awal penyelesaian dokumen dan proses hukum terkait akuisisi PT MSI,” ujar Irianto Santoso dalam keterangan resmi, Kamis (20/11/2025).\n\nPT MSI merupakan anak perusahaan dari Mah Sing Group Berhad, sebuah kelompok usaha konglomerasi asal Malaysia yang memiliki portofolio bisnis luas meliputi sektor properti, industri plastik, dan manufaktur.\n\nDia mengatakan, langkah akuisisi tersebut tentunya akan memperkuat posisi Dharma Polimetal (DRMA) di industri manufaktur komponen plastik untuk kendaraan roda empat (4W).\n\n“Akuisisi ini juga sejalan dengan strategiinovasi perusahaan dalam meningkatkan diversifikasi dan ekspansi bisnis,” tambahnya.\n\nSementara itu, manajemen Dharma Polimetal (DRMA) optimistis perseroan akan dapat meraih target penjualan sebesar Rp 6 triliun pada tahun 2025.\n\nPada periode Januari-September 2025, penjualan DRMA tercatat tumbuh 9,20% (year on year/YoY) menjadi Rp 4,39 triliun. Sedangkan, laba bersih meningkat 1,69% YoY menjadi Rp 428,11 miliar.\n\nSegmen roda dua (2W) yang mencatatkan penjualan sebesar Rp 2,72 triliun, merupakan kontributor utama pendapatan DRMA.\n\nSegmen 2W ini menyumbang 62% dari total penjualan konsolidasi DRMA, didukung oleh inovasi yang dilakukan untuk meningkatkan pangsa pasar yang turut mendorong pertumbuhan kinerja secara keseluruhan.\n\nSementara itu, saham DRMA bergerak menanjak 1,99% ke harga Rp 1.025 per saham pada perdagangan Jumat (21/11/2025).\n\nFollow ChannelTelegram Officialkami untuk update artikel-artikel investor.id\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: PT Teknologi Karya Digital Nusa Tbk (TRON) atau TKDN menjalin kemitraan strategis dengan National Battery Research Institute (NBRI) melalui penandatanganan nota kesepahaman (MoU). MoU ini terkait untuk mempercepat pengembangan teknologi digitalisasi infrastruktur kendaraan listrik dan sistem penyimpanan energi baterai (battery energy storage system/BESS) di Indonesia.\n\nMoU ini ditandatangani oleh Direktur Utama TRON, David Santoso, dan Founder NBRI, Evvy Kartini. Kolaborasi ini memadukan keunggulan masing-masing pihak untuk mengakselerasi pengembangan teknologi smart mobility, sekaligus meningkatkan kualitas dan keamanan baterai yang digunakan dalam ekosistem kendaraan listrik nasional.\n\nKerja sama antara TRON dan NBRI mencakup pengembangan teknologismart mobilityserta pengembanganresearch and developmentproduk baterai untuk kendaraan bermotor listrik berbasis baterai dan BESS.\n\nSelain itu, kedua pihak juga akan berkolaborasi dalam pengujian, pengukuran, verifikasi kinerja, danbattery testinguntuk mendukung standardisasi dan peningkatan kualitas baterai. Uji coba sistem monitoring kendaraan listrik, peningkatan kapasitas SDM, pelatihan teknologi, hingga berbagai bentuk kolaborasi lain yang relevan juga menjadi bagian dari ruang lingkup kerja sama ini.\n\nDirektur Utama TRON, David Santoso, menjelaskan bahwa kemitraan ini menjadi tonggak penting bagi perusahaan.\n\n“Kerja sama dengan NBRI menjadi penggerak utama bagi PT TKDN Tbk untuk mewujudkan visi kami sebagai pemimpin di bidangbattery as a service(BaaS) dangreen mobilitydi Indonesia. Sinergi ini memperkuat kemampuan kami menghadirkan solusi teknologi yang inovatif dan berkelanjutan bagi ekosistem transportasi dan energi masa depan,” ungkapnya dalam keterangan resmi, Jumat (21/11/2025).\n\nFounder NBRI, \xa0Evvy Kartini, menegaskan keunggulan kompetensi teknologi yang dimiliki NBRI. “NBRI memiliki kapabilitas hulu untuk memproduksi katoda baterai berbasis nikel berkualitas tinggi. Kami juga dapat memberikan sertifikasi untuk memastikan bahwa produk baterai memenuhi standar keamanan global. Kolaborasi ini memastikan bahwa baterai yang akan dikembangkan di Indonesia tidak hanya unggul secara teknologi, tetapi juga memenuhi standar internasional,” imbuhnya.\n\nKemitraan ini menjadi wujud nyata kolaborasi antara sektor teknologi dan riset dalam memperkuat ekosistem kendaraan listrik nasional. PT TKDN Tbk, melalui TRON-X Solutions dan Renewable Energy Solutions, akan mengintegrasikan platform digital berbasis AI dan teknologi energi terbarukan dengan kemampuan riset dan teknologi baterai mutakhir dari NBRI guna menghadirkan transportasi listrik yang lebih efisien, terjangkau, dan berkelanjutan.\n\nEditor:Theresa Sandra Desfika(thresa.lepaslandas@gmail.com)\n\nFollow ChannelTelegram Officialkami untuk update artikel-artikel investor.id\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Komisaris Independen PT Telkom Indonesia (Persero) Tbk (TLKM) mengumumkan pengunduran diri dari perseroan.\n\nSVP Corporate Secretary TLKM Jati Widagdo mengungkap, Telkom Indonesia (TLKM) telah menerima surat pengundurkan diri Yohanes Surya sebagai Komisaris Independen perseroan pada 20 November 2025.\n\n"Pada tanggal 20 November 2025 perseroan telah menerima surat pengunduran diri dari Bapak Yohanes Surya selaku Komisaris Independen PT Telkom Indonesia (Persero) Tbk," kata Jati dalam keterbukaan informasi Bursa Efek Indonesia (BEI), Jumat (21/11/2025).\n\nDia menegaskan, pengunduran diri Komisaris Independen tersebut tidak memiliki dampak material terhadap kelangsungan usaha perseroan.\n\nSelanjutnya, perseroan akan mengambil langkah-langkah yang diperlukan berkaitan\xa0dengan surat pengunduran diri yang diajukan oleh Yohanes Surya sesuai dengan ketentuan yang berlaku.\n\nSementara itu, Telkom Indonesia (TLKM) juga berencana\xa0menggelar Rapat Umum Pemegang Saham Luar Biasa (RUPLSB) pada 12 Desember 2025.\n\nSejumlah mata acara akan dibahas, di antaranya yakni persetujuan atas rencana perseroan untuk melakukan pemisahan sebagian bisnis dan asetwholesale fiber connectivity(tahap I) yang merupakan bagian dari rencana pengalihan seluruh bisnis dan asetwholesale fiber connectivitykepada PT Telkom Infrastruktur Indonesia. Lalu, juga perubahan susunan pengurus perseroan.\n\nPerlu diketahui, Yohanes Surya diangkat menjadi Komisaris Independen PT Telkom Indonesia (Persero) Tbk (TLKM) dalam Rapat Umum Pemegang Saham Tahunan (RUPST) pada 27 Mei 2025.\n\nSeiring adanya informasi tersebut, saham TLKM terpantau anjlok 3,3% ke harga Rp 3.530 per saham pada perdagangan Jumat (21/11/2025).\n\nFollow ChannelTelegram Officialkami untuk update artikel-artikel investor.id\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Indeks harga saham gabungan (IHSG) diprediksi akan berkonsolidasi pada perdagangan pekan depan, Senin (24/11/2025).\n\nPhintraco Sekuritas menjelaskan dalam risetnya, IHSG ditutup melemah pada level 8.414,3 (-0.07%) pada perdagangan Jumat (21/11/2025).\n\nTim risetnya menjelaskan, koreksi IHSG antara lain dipicu oleh melemahnya indeks bursa global, dan regional di tengah sentimen negatif tekanan jual saham sektor teknologi, serta memudarnya ekspektasi akan penurunan suku bunga the Fed di Desember 2025.\n\nSecara teknikal, MACD membentukDeath CrossdanStoachasticRSI berada di area pivot. IHSG ditutup di bawah level MA5.\n\n“Sehingga diperkirakan IHSG masih akan berkonsolidasi di kisaran 8.350-8.450 dalam jangka pendek, selama belum mampu ditutup di atas level 8.450 dengan didukung volume besar,” tulisnya dalam riset, Jumat sore (21/11/2025).\n\nMayoritas indeks di bursa Asia ditutup melemah, Jumat (21/11/2025). Indeks bursa Eropa dibuka melemah dan indeksfuturesdi Wall Street bergerak menguat moderat, Jumat (21/11/2025). IHSG selama sepekan ditutup menguat 0,52%.\n\nUang beredar dalam arti luas (M2) Indonesia tumbuh 7,7% YoY mencapai Rp 9.783,1 triliun di Oktober 2025 dari pertumbuhan 8% YoY di September 2025, Jumat (21/11/2025).\n\nPertumbuhan yang sedikit melambat ini sejalan dengan pertumbuhan kredit bulan Oktober yang juga melambat dibandingkan bulan sebelumnya.\n\nSementara itu, laju inflasi Jepang naik menjadi 3% YoY di Oktober 2025 dari 2,9% YoY di September 2025. Ini merupakan level inflasi tertinggi sejak Juli 2025.\n\nPemerintahan Jepang menyetujui paket stimulus senilai 21,3 triliun yen, sebagai upaya mendorong pertumbuhan ekonomi dan membantu konsumen yang terdampak inflasi.\n\nPhintraco Sekuritas memberikan rekomendasi saham yang dapat diperhatikan, antara lain saham MDKA, SMGR, HMSP, PGEO, EMTK dan CBDK untuktradingSenin (24/11/2025).\n\nFollow ChannelTelegram Officialkami untuk update artikel-artikel investor.id\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Indeks harga saham gabungan (IHSG) hari ini, Jumat (21/11/2025), ditutup menurun tipis 5,56 poin (0,07%) ke level 8.414,3.\n\nSejumlah saham terpantau memberikan cuan besar mulai dari saham BUKK hingga GPSO dengan lonjakan harga 24,59% sampai 25%.\n\nAdapun total nilai transaksi di bursa mencapai Rp 16,13 triliun. Sebanyak 295 saham naik, sedangkan 366 saham turun dan 295 saham stagnan. Volume perdagangan sebanyak 32,86 miliar saham dengan frekuensi sebanyak 1,92 juta kali.\n\nSejumlah sektor saham menguat pada penutupan pasar hari ini. Sektor saham yang menguat paling tinggi yakni sektor teknologi sebesar 2,72%.\n\nDiikuti, penguatan di sektor perindustrian sebesar 0,85%, sektor barang konsumen primer 0,66%, sektor barang baku 0,65%, sektor properti 0,58%, dan sektor kesehatan 0,4%.\n\nSebaliknya, pelemahan melanda sektor keuangan 0,61%, sektor transportasi 0,6%, sektor infrastruktur 0,58%, sektor barang konsumen non-primer 0,49%, dan sektor energi 0,29%.\n\nPilarmas Investindo Sekuritas menilai, pelemahan ini efek aksi profit taking dari investor domestik setelah IHSG menyentuh ATH. “Pasar bergerak sangat hati-hati dalam posisi baru, terutama menjelang akhir pekan,” tulis Pilarmas dalam risetnya, Jumat (21/11/2025).\n\nPelemahan IHSG terjadi seiring aksi jual di Wall Street, setelah data ketenagakerjaan Amerika Serikat (AS) justru memperkeruh ekspektasi pasar mengenai prospek pemangkasan suku bunga The Fed.\n\nGubernur The Fed Michael Barr turut memperingatkan bahwa bank sentral harus berhati-hati dalam melanjutkan pemangkasan suku bunga, mengingat inflasi masih berada di atas target.\n\nPilarmas menegaskan, situasi tersebut membuat pelaku pasar global memilih menahan diri dan mengurangi eksposur pada aset berisiko, termasuk pasar saham Asia yang juga melemah serentak.\n\nFollow ChannelTelegram Officialkami untuk update artikel-artikel investor.id\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Wakil Menteri Keuangan (Wamenkeu) Suahasil Nazara mengatakan pemerintah sudah membelanjakan anggaran sebesar Rp 20,3 triliun untuk subsidi bunga kredit usaha rakyat (KUR) per 31 Oktober 2025. Dana tersebut\xa0dipakai untuk mensubsidi bunga penyaluran KUR sebesar Rp 228,1 triliun.\n\n“Realisasi pembayaran subsidi bunga sudah Rp 20,3 triliun untuk pembayaran tagihan subsidi bunga selama 2025 tidak termasuk carry over,” ucap Suahasil dalam konferensi pers APBN KiTa\xa0Edisi November 2025 di kantor Kemenkeu, Jakarta Kamis (20/11/2025).\n\nRealisasi subsidi bunga KUR sebesar Rp 20,3 triliun ini sudah 53,1% dari pagu \xa0senilai Rp 38,28 \xa0triliun. Sedangkan realisasi KUR senilai Rp 228,1 triliun sudah mencapai \xa079,7% dari pagu 2025 Rp 286 triliun.\n\nSubsidi bunga KUR ini dibayarkan oleh APBN kepada bank penyalur, sehingga nasabah KUR dapat menikmati bunga KUR sebesar 6%.\n\n“Artinya untuk tahun 2025 untuk bulan November dan Desember masih ada pagu kredit KUR yang bisa diakses oleh masyarakat totalnya sekitar Rp 53 triliun masih belum terrealisasi,” tutur Suahasil.\n\nDana dalam KUR sudah disalurkan ke 3,9 juta debitur. Bila dilihat menurut sektor maka realisasi KUR terbagi dalam sektor perdagangan (39,3%), pertanian (38,1%), sektor lainnya (15 %), perikanan (1,5%), industri pengolahan (6%), dan konstruksi (0,1%).\n\n“Penerima kur saat ini tercatat sekitar 3,9 juta debitur dan sektornya terutama adalah sektor perdagangan dan sektor pertanian dan sektor-sektor lain juga. Namun sektor yang paling besar adalah perdagangan dan pertanian,” terang dia.\n\nEditor:Natasha Khairunisa Amani(tasha.amani@gmail.com)\n\nFollow ChannelTelegram Officialkami untuk update artikel-artikel investor.id\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 3, "type": Entity Type 3}, ....]. \n\nParagraph: Kredit bermasalah yang dipotret dari rasionon-performing loan(NPL) untuk jenis kredit usaha rakyat (KUR) hingga Oktober 2025 adalah sebesar 2,28%. Pemerintah menilai, KUR menjadi program pembiayaan yang paling masih dan efektif.\n\nBerdasarkan keterangan resmi Kementerian Bidang Perekonomian pada Jumat (21/11/2025), hingga 31 Oktober 2025, penyaluran KUR telah mencapai Rp 228,05 triliun kepada 3,87 juta debitur. Nilai pencairan KUR tersebut telah mencakup sekitar 80,16% dari proyeksi tahun ini yang mencapai Rp 284,48 triliun kepada 5,01 juta debitur dengan penyerapan tenaga kerja mencapai 20 juta orang.\n\nPenyaluran KUR untuk sektor produksi mencapai 60,7% dengan fokus pada pertanian Rp 86,8 triliun dan jasa Rp 17,7 triliun. Sedangkan untuk sektor non produksi atau perdagangan sebesar Rp 89,68 triliun.\n\nLebih dari sekadar angka pencairan, KUR menunjukkan kualitas eksekusi dengan tingkat kredit bermasalah atau NPL hanya 2,28%, separuh dari rata-rata NPL kredit UMKM perbankan yang mencapai 4,55%.\n\nProgram KUR juga menunjukkan inklusivitas dengan skema khusus yang menjangkau segmen spesifik. KUR Penempatan Pekerja Migran Indonesia (KUR PMI) mencatatkan penyaluran sebesar Rp 64,53 miliar kepada 2.182 Pekerja Migran Indonesia dan peserta magang luar negeri.\n\nSementara itu, target debitur KUR baru berjalan optimal dengan capaian 2,34 juta debitur (70,6% dari target 2025) dan pemenuhan target debitur KUR graduasi mencapai 79,13% dari target 2025 atau sebanyak 1,17 juta debitur.\n\n“Dari hasilmonitoringdan evaluasi kinerja penyaluran Kredit Usaha Rakyat (KUR) tahun 2025 yang dilakukan oleh Sekretariat Komite Kebijakan Pembiayaan Bagi UMKM, KUR membuktikan diri sebagai program pembiayaan UMKM paling masif dan efektif,” ungkap Kemenko Perekonomian dalam keterangan resmi.\n\nKe depan, target KUR 2026 akan disesuaikan dengan arah program prioritas nasional, proyeksi pertumbuhan usaha produktif, dan kapasitas fiskal. Target tersebut tercermin pada penetapan target porsi penyaluran di sektor produksi dan peningkatan porsi debitur KUR baru serta debitur KUR graduasi. Selanjutnya, untuk KUR PMI dioptimalkan penyalurannya pada calon PMI guna mengurangi beban biaya penempatan pahlawan devisa Indonesia.\n\nSebelumnya, Komite Kebijakan Pembiayaan UMKM menargetkan plafon penyaluran KUR naik menjadi Rp 320 triliun pada tahun 2026. Dari target tersebut penyaluran sektor produksi ditargetkan mencapai 65% dari target atau naik 5% dari target tahun 2025.\n\n“Saya tadi mendapatkan target di 2026 sebesar Rp 320 triliun untuk didorong ke sektor UMKM. Lalu yang dialokasikan ke sektor produksi 65%. Jadi dapat penugasan dari Komite Kebijakan Pembiayaan UMKM naik sekitar 5%,” beber Menteri UMKM, Maman Abdurrahman di kantor Kementerian Koordinator Bidang Perekonomian pada Senin (17/11/2025).\n\nFollow ChannelTelegram Officialkami untuk update artikel-artikel investor.id\n\n Key Words: ', 'Here is a paragraph. Please extract all the named entity in the paragraph with format of [{"entity": Entity Name 1, "type": Entity Type 1}, {"entity": Entity Name 2, "type": Entity Type 2}, {"entity": Entity Name 

In [32]:
ner_res = []
summary_res = []

In [35]:
async def run_prompt(processed_prompt):
    final_prompt = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": processed_prompt}
    ]

    response = await client.chat.completions.create(
        model="qwen/qwen3-30b-a3b-instruct-2507",
        messages=final_prompt
    )

    return {
        "prompt": processed_prompt,
        "answer": response.choices[0].message.content
    }

In [36]:
async def run_ner_prompts():
    tasks = [run_prompt(p) for p in processed_ner_prompts]
    results = await asyncio.gather(*tasks)
    return results

async def run_summary_prompts():
    tasks = [run_prompt(p) for p in processed_summary_prompts]
    results = await asyncio.gather(*tasks)
    return results

async def main():
    results = await asyncio.gather(
        run_ner_prompts(),
        run_summary_prompts()
    )
    return results

In [39]:
res = await main()

In [40]:
files_length = len(os.listdir())

with open(f"{files_length}.json", "w") as f:
    json.dump(res, f, indent=2)